DROP DATABASE IF EXISTS RetailDB;

CREATE DATABASE RetailDB;

USE RetailDB;

DROP TABLE IF EXISTS SalesTransactions;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Categories;

CREATE TABLE Categories
(
    CategoryId INT PRIMARY KEY,
    CategoryName VARCHAR(50)
);

CREATE TABLE Products
(
    ProductId INT PRIMARY KEY,
    ProductName VARCHAR(100),
    CategoryId INT,
    StockCount INT,
    ExpiryDate DATE,
    FOREIGN KEY(CategoryId) REFERENCES Categories(CategoryId)
);

CREATE TABLE SalesTransactions
(
    SaleId INT PRIMARY KEY,
    ProductId INT,
    Qty INT,
    Price DECIMAL(10,2),
    SoldOn DATE,
    FOREIGN KEY(ProductId) REFERENCES Products(ProductId)
);

INSERT INTO Categories VALUES
(1,'Dairy'),
(2,'Beverages'),
(3,'Snacks'),
(4,'Bakery'),
(5,'Household');

INSERT INTO Products VALUES
(101,'Milk',1,80,'2026-06-28'),
(102,'Curd',1,30,'2026-07-10'),
(103,'Bread',4,70,'2026-06-26'),
(104,'Chips',3,120,'2027-01-15'),
(105,'Tea Powder',2,60,'2027-05-12'),
(106,'Detergent',5,45,'2028-03-20'),
(107,'Butter',1,90,'2026-06-27'),
(108,'Biscuits',3,25,'2027-02-18');

INSERT INTO SalesTransactions VALUES
(1,101,5,60,'2026-06-15'),
(2,101,8,96,'2026-06-20'),
(3,103,4,120,'2026-06-19'),
(4,104,10,250,'2026-05-28'),
(5,105,3,450,'2026-06-12'),
(6,107,2,110,'2026-06-18'),
(7,103,6,180,'2026-06-21'),
(8,101,4,48,'2026-06-22');



-- Display products that will expire within the next 7 days and have more than 50 items in stock.
SELECT
p.ProductId,
p.ProductName,
p.StockCount,
p.ExpiryDate
FROM Products p
WHERE
p.ExpiryDate BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 7 DAY)
AND
p.StockCount > 50;

-- Display products that have not been sold in the last 2 months.
SELECT
p.ProductId,
p.ProductName
FROM Products p
LEFT JOIN SalesTransactions s
ON p.ProductId=s.ProductId
AND s.SoldOn>=DATE_SUB(CURDATE(),INTERVAL 2 MONTH)
WHERE s.ProductId IS NULL;

-- Display total revenue generated by each product category for the current month.
SELECT
c.CategoryName,
SUM(s.Price) AS Revenue
FROM Categories c
JOIN Products p
ON c.CategoryId=p.CategoryId
JOIN SalesTransactions s
ON p.ProductId=s.ProductId
WHERE
MONTH(s.SoldOn)=MONTH(CURDATE())
AND
YEAR(s.SoldOn)=YEAR(CURDATE())
GROUP BY c.CategoryName
ORDER BY Revenue DESC;

-- Display the total number of units sold for each product.
SELECT
p.ProductName,
SUM(s.Qty) AS UnitsSold
FROM Products p
JOIN SalesTransactions s
ON p.ProductId=s.ProductId
GROUP BY
p.ProductId,
p.ProductName
ORDER BY UnitsSold DESC;

-- Display the number of products available in each category.
SELECT
CategoryName,
COUNT(ProductId) AS ProductCount
FROM Categories c
LEFT JOIN Products p
ON c.CategoryId=p.CategoryId
GROUP BY
CategoryName;

-- Display all products sorted by available stock.
SELECT
ProductName,
StockCount
FROM Products
ORDER BY StockCount DESC;

-- Display the total number of products.
SELECT
COUNT(*) AS TotalProducts
FROM Products;

-- Display the total revenue from all sales.
SELECT
SUM(Price) AS TotalRevenue
FROM SalesTransactions;

-- Display the average sale amount.
SELECT
AVG(Price) AS AverageSale
FROM SalesTransactions;

-- Display all products sorted by expiry date.
SELECT
ProductName,
ExpiryDate
FROM Products
ORDER BY ExpiryDate;
